name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
env:
  AZURE_FUNCTION_NAME: NetsuiteBPIIntegration20230414203211
  AZURE_FUNCTION_PACKAGE_PATH: "./publish"
  Values__Message: ${{ secrets.MESSAGE }}

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./Netsuite.BPIIntegration.sln
        
      - name: Build
        run: dotnet build ./Netsuite.BPIIntegration.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Netsuite.BPIIntegration.sln --configuration Release --no-build --output '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTION_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_FUNCTION_PACKAGE_PATH }}"

        
